Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 13, in <module>
    structure = get_gs_structure()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 24, in get_gs_structure
    with open("./credfile/googlesheets_names_and_ids.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: './credfile/googlesheets_names_and_ids.json'
준비 끝
준비까지 :  15.327084064483643 초
************************ 2022-11-09 04:03:17.847460 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 67, in importrange
    to_worksheet = gs.auth.open_by_url(default_gsurl + structure[paste_ssname]["id"]).get_worksheet_by_id(
AttributeError: 'Spreadsheet' object has no attribute 'get_worksheet_by_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  14.938574075698853 초
************************ 2022-11-09 04:13:17.160831 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 67, in importrange
    to_worksheet = gs.auth.open_by_url(default_gsurl + structure[paste_ssname]["id"]).get_worksheet_by_id(
AttributeError: 'Spreadsheet' object has no attribute 'get_worksheet_by_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 1, in <module>
    from gspread_dataframe import set_with_dataframe
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 13, in <module>
    from gspread.models import Cell
ModuleNotFoundError: No module named 'gspread.models'
준비 끝
준비까지 :  13.890550374984741 초
************************ 2022-11-09 04:22:16.066183 함수 실행************************
복사 끝
주문량 예측 Promo - > SKU별 수요량 예측 - 주문량 예측 초 걸려 작업 완료
준비 끝
준비까지 :  14.43748950958252 초
************************ 2022-11-09 04:33:17.027908 함수 실행************************
복사 끝
201.05995988845825 초 걸려 작업 완료
준비 끝
준비까지 :  15.730751752853394 초
************************ 2022-11-09 04:43:18.299666 함수 실행************************
복사 끝
191.29376029968262 초 걸려 작업 완료
준비 끝
준비까지 :  13.477575302124023 초
************************ 2022-11-09 04:53:15.544573 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 153, in work
    importrange(copy_ssname="주문량 예측 Promo", copy_wsname="Promo 첫전환 주문량 예측", range=["NJ2","ABK7"], paste_ssname="주문량 예측", paste_wsname="주문량 예측 시트", paste="B23")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 66, in importrange
    from_data = gs.open_sheet(default_gsurl + structure[copy_ssname]["id"], copy_wsname)
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 21, in open_sheet
    return get_as_dataframe(self.auth.open_by_url(sheet_url).worksheet(tab_name), evaluate_formulas=True, header = None)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 189, in get_as_dataframe
    all_values = _get_all_values(worksheet, evaluate_formulas)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 140, in _get_all_values
    "dateTimeRenderOption": "FORMATTED_STRING",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 182, in values_get
    r = self.client.request("get", url, params=params)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.45503830909729 초
************************ 2022-11-09 05:03:17.472190 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  13.880852937698364 초
************************ 2022-11-09 05:13:15.965587 함수 실행************************
복사 끝
188.7156219482422 초 걸려 작업 완료
준비 끝
준비까지 :  13.510144472122192 초
************************ 2022-11-09 05:23:15.191511 함수 실행************************
복사 끝
202.12218189239502 초 걸려 작업 완료
준비 끝
준비까지 :  17.60447931289673 초
************************ 2022-11-09 05:33:19.654917 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  13.421316385269165 초
************************ 2022-11-09 05:43:15.724924 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 141, in work
    importrange(copy_ssname="주문량 예측 Promo", copy_wsname="Promo Plan (UA)", paste_ssname="주문량 예측", paste_wsname="신규유입자 계산", range=["A2","D7"], paste="A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 66, in importrange
    from_data = gs.open_sheet(default_gsurl + structure[copy_ssname]["id"], copy_wsname)
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 21, in open_sheet
    return get_as_dataframe(self.auth.open_by_url(sheet_url).worksheet(tab_name), evaluate_formulas=True, header = None)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 189, in get_as_dataframe
    all_values = _get_all_values(worksheet, evaluate_formulas)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 140, in _get_all_values
    "dateTimeRenderOption": "FORMATTED_STRING",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 182, in values_get
    r = self.client.request("get", url, params=params)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  14.495971202850342 초
************************ 2022-11-09 05:53:16.279400 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  22.60917329788208 초
************************ 2022-11-09 06:03:25.146381 함수 실행************************
복사 끝
196.57922673225403 초 걸려 작업 완료
준비 끝
준비까지 :  15.987273931503296 초
************************ 2022-11-09 06:13:18.326284 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  14.488760948181152 초
************************ 2022-11-09 06:23:16.478772 함수 실행************************
복사 끝
212.2260766029358 초 걸려 작업 완료
준비 끝
준비까지 :  17.399092197418213 초
************************ 2022-11-09 06:33:20.056084 함수 실행************************
복사 끝
214.91131854057312 초 걸려 작업 완료
준비 끝
준비까지 :  15.152048826217651 초
************************ 2022-11-09 06:43:17.629477 함수 실행************************
복사 끝
198.90953850746155 초 걸려 작업 완료
준비 끝
준비까지 :  14.124326944351196 초
************************ 2022-11-09 06:53:16.657231 함수 실행************************
복사 끝
212.65768957138062 초 걸려 작업 완료
준비 끝
준비까지 :  15.731778383255005 초
************************ 2022-11-09 07:03:17.659468 함수 실행************************
복사 끝
209.40300369262695 초 걸려 작업 완료
준비 끝
준비까지 :  17.23848295211792 초
************************ 2022-11-09 07:13:19.543695 함수 실행************************
복사 끝
220.1123011112213 초 걸려 작업 완료
준비 끝
준비까지 :  13.550600290298462 초
************************ 2022-11-09 07:23:16.023177 함수 실행************************
복사 끝
233.32833051681519 초 걸려 작업 완료
준비 끝
준비까지 :  18.830559015274048 초
************************ 2022-11-09 07:33:21.923886 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.45265793800354 초
************************ 2022-11-09 07:43:18.084507 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.38154673576355 초
************************ 2022-11-09 07:53:17.806379 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  18.174429416656494 초
************************ 2022-11-09 08:03:20.390103 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 141, in work
    importrange(copy_ssname="주문량 예측 Promo", copy_wsname="Promo Plan (UA)", paste_ssname="주문량 예측", paste_wsname="신규유입자 계산", range=["A2","D7"], paste="A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 66, in importrange
    from_data = gs.open_sheet(default_gsurl + structure[copy_ssname]["id"], copy_wsname)
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 21, in open_sheet
    return get_as_dataframe(self.auth.open_by_url(sheet_url).worksheet(tab_name), evaluate_formulas=True, header = None)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 189, in get_as_dataframe
    all_values = _get_all_values(worksheet, evaluate_formulas)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 140, in _get_all_values
    "dateTimeRenderOption": "FORMATTED_STRING",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 182, in values_get
    r = self.client.request("get", url, params=params)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  16.285924434661865 초
************************ 2022-11-09 08:13:18.330892 함수 실행************************
복사 끝
232.61034059524536 초 걸려 작업 완료
준비 끝
준비까지 :  16.89397144317627 초
************************ 2022-11-09 08:23:19.572784 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.750646352767944 초
************************ 2022-11-09 08:33:18.105465 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  14.329441785812378 초
************************ 2022-11-09 08:43:16.735725 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 141, in work
    importrange(copy_ssname="주문량 예측 Promo", copy_wsname="Promo Plan (UA)", paste_ssname="주문량 예측", paste_wsname="신규유입자 계산", range=["A2","D7"], paste="A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 66, in importrange
    from_data = gs.open_sheet(default_gsurl + structure[copy_ssname]["id"], copy_wsname)
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 21, in open_sheet
    return get_as_dataframe(self.auth.open_by_url(sheet_url).worksheet(tab_name), evaluate_formulas=True, header = None)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 189, in get_as_dataframe
    all_values = _get_all_values(worksheet, evaluate_formulas)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 140, in _get_all_values
    "dateTimeRenderOption": "FORMATTED_STRING",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 182, in values_get
    r = self.client.request("get", url, params=params)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  14.615518808364868 초
************************ 2022-11-09 08:53:16.959379 함수 실행************************
복사 끝
224.5433120727539 초 걸려 작업 완료
준비 끝
준비까지 :  23.20866560935974 초
************************ 2022-11-09 09:03:25.463574 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.427503108978271 초
************************ 2022-11-09 09:13:17.595879 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 141, in work
    importrange(copy_ssname="주문량 예측 Promo", copy_wsname="Promo Plan (UA)", paste_ssname="주문량 예측", paste_wsname="신규유입자 계산", range=["A2","D7"], paste="A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 66, in importrange
    from_data = gs.open_sheet(default_gsurl + structure[copy_ssname]["id"], copy_wsname)
  File "/home/ubuntu/automation/DemandForecastOrdersheets/utils.py", line 21, in open_sheet
    return get_as_dataframe(self.auth.open_by_url(sheet_url).worksheet(tab_name), evaluate_formulas=True, header = None)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 189, in get_as_dataframe
    all_values = _get_all_values(worksheet, evaluate_formulas)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 140, in _get_all_values
    "dateTimeRenderOption": "FORMATTED_STRING",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 182, in values_get
    r = self.client.request("get", url, params=params)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  22.12459373474121 초
************************ 2022-11-09 09:23:24.566855 함수 실행************************
복사 끝
247.42063307762146 초 걸려 작업 완료
준비 끝
준비까지 :  14.302533864974976 초
************************ 2022-11-09 09:33:16.228167 함수 실행************************
복사 끝
219.80009603500366 초 걸려 작업 완료
준비 끝
준비까지 :  17.84725308418274 초
************************ 2022-11-09 09:43:20.519221 함수 실행************************
복사 끝
238.1015501022339 초 걸려 작업 완료
준비 끝
준비까지 :  15.55975604057312 초
************************ 2022-11-09 09:53:18.409485 함수 실행************************
복사 끝
233.34947776794434 초 걸려 작업 완료
준비 끝
준비까지 :  19.7357177734375 초
************************ 2022-11-09 10:03:22.002896 함수 실행************************
복사 끝
226.95559072494507 초 걸려 작업 완료
준비 끝
준비까지 :  17.218522548675537 초
************************ 2022-11-09 10:13:19.388861 함수 실행************************
복사 끝
218.64678692817688 초 걸려 작업 완료
준비 끝
준비까지 :  22.0274395942688 초
************************ 2022-11-09 10:23:23.887578 함수 실행************************
복사 끝
235.92226815223694 초 걸려 작업 완료
준비 끝
준비까지 :  18.481587409973145 초
************************ 2022-11-09 10:33:21.618586 함수 실행************************
복사 끝
240.481760263443 초 걸려 작업 완료
준비 끝
준비까지 :  14.508981466293335 초
************************ 2022-11-09 10:43:17.100589 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  16.72219204902649 초
************************ 2022-11-09 10:53:19.099411 함수 실행************************
복사 끝
230.84408593177795 초 걸려 작업 완료
준비 끝
준비까지 :  15.070024013519287 초
************************ 2022-11-09 11:03:17.428394 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
준비 끝
준비까지 :  15.96659231185913 초
************************ 2022-11-09 11:13:17.878992 함수 실행************************
복사 끝
214.27726435661316 초 걸려 작업 완료
준비 끝
준비까지 :  14.420302391052246 초
************************ 2022-11-09 11:23:16.712163 함수 실행************************
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 128, in work
    start = time.time()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 123, in importrange
    row=paste_fromrow_py,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
************************ 2022-11-09 11:33:02.329253 함수 실행************************
준비 끝
준비까지 :  16.766706466674805 초
Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 179, in <module>
    worktime = work()
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 129, in work
    importrange(copy_ssname = "AOQ_RAW", copy_wsname= "AOQ_firstRe", paste_ssname="주문량 예측 Promo", paste_wsname="AOQ_firstRe(importrange)", range=["2","4"], paste = "A1")
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 124, in importrange
    col=paste_fromcolumn_py)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 279, in set_with_dataframe
    _resize_to_minimum(worksheet, y, x)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread_dataframe.py", line 130, in _resize_to_minimum
    worksheet.resize(desired_rows, desired_cols)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/worksheet.py", line 1073, in resize
    return self.spreadsheet.batch_update(body)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/spreadsheet.py", line 132, in batch_update
    "post", SPREADSHEET_BATCH_UPDATE_URL % self.id, json=body
  File "/home/ubuntu/.local/lib/python3.7/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 182, in <module>
    print("==============", sec, "에서 문제가 생겼습니다.==============")
NameError: name 'sec' is not defined
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
  File "/home/ubuntu/automation/DemandForecastOrdersheets/main.py", line 10
    global sec
    ^
SyntaxError: name 'sec' is assigned to before global declaration
************************ 2022-11-09 13:23:02.340032 함수 실행************************
준비 끝
준비까지 :  13.66981053352356 초
복사 끝
207.18980860710144 초 걸려 작업 완료
************************ 2022-11-09 13:33:02.697767 함수 실행************************
준비 끝
준비까지 :  14.37131381034851 초
복사 끝
209.1695008277893 초 걸려 작업 완료
************************ 2022-11-09 13:43:01.717974 함수 실행************************
준비 끝
준비까지 :  16.34175682067871 초
복사 끝
220.29463696479797 초 걸려 작업 완료
************************ 2022-11-09 13:53:02.363504 함수 실행************************
준비 끝
준비까지 :  14.705232620239258 초
복사 끝
230.53925585746765 초 걸려 작업 완료
************************ 2022-11-09 14:03:02.057838 함수 실행************************
준비 끝
준비까지 :  15.75907015800476 초
복사 끝
241.16952753067017 초 걸려 작업 완료
************************ 2022-11-09 14:13:02.243051 함수 실행************************
준비 끝
준비까지 :  16.19005012512207 초
복사 끝
237.53347778320312 초 걸려 작업 완료
************************ 2022-11-09 14:23:02.038213 함수 실행************************
준비 끝
준비까지 :  13.559258699417114 초
복사 끝
225.33474707603455 초 걸려 작업 완료
************************ 2022-11-09 14:33:02.280350 함수 실행************************
준비 끝
준비까지 :  14.041738986968994 초
복사 끝
228.65845441818237 초 걸려 작업 완료
************************ 2022-11-09 14:43:02.040418 함수 실행************************
준비 끝
준비까지 :  13.1370689868927 초
복사 끝
218.36479353904724 초 걸려 작업 완료
************************ 2022-11-09 14:53:02.353574 함수 실행************************
준비 끝
준비까지 :  12.879584789276123 초
복사 끝
223.79186391830444 초 걸려 작업 완료
************************ 2022-11-09 15:03:02.263549 함수 실행************************
준비 끝
준비까지 :  14.140289306640625 초
복사 끝
221.71825170516968 초 걸려 작업 완료
************************ 2022-11-09 15:13:02.131264 함수 실행************************
준비 끝
준비까지 :  14.562016248703003 초
복사 끝
220.84263730049133 초 걸려 작업 완료
************************ 2022-11-09 15:23:02.130708 함수 실행************************
준비 끝
준비까지 :  13.917085409164429 초
복사 끝
209.84099674224854 초 걸려 작업 완료
************************ 2022-11-09 15:33:02.483763 함수 실행************************
준비 끝
준비까지 :  13.523701429367065 초
복사 끝
229.65235209465027 초 걸려 작업 완료
************************ 2022-11-09 15:43:02.332032 함수 실행************************
준비 끝
준비까지 :  15.197803258895874 초
복사 끝
227.78210997581482 초 걸려 작업 완료
************************ 2022-11-09 15:53:02.555755 함수 실행************************
준비 끝
준비까지 :  13.628562450408936 초
복사 끝
224.0277922153473 초 걸려 작업 완료
************************ 2022-11-09 16:03:02.569504 함수 실행************************
준비 끝
준비까지 :  14.48265290260315 초
복사 끝
208.51726412773132 초 걸려 작업 완료
************************ 2022-11-09 16:13:02.145039 함수 실행************************
준비 끝
준비까지 :  13.564208507537842 초
복사 끝
214.2476830482483 초 걸려 작업 완료
************************ 2022-11-09 16:23:02.505218 함수 실행************************
준비 끝
준비까지 :  15.875561475753784 초
복사 끝
241.02978706359863 초 걸려 작업 완료
************************ 2022-11-09 16:33:02.652005 함수 실행************************
준비 끝
준비까지 :  16.80833411216736 초
복사 끝
253.38932967185974 초 걸려 작업 완료
************************ 2022-11-09 16:43:02.193896 함수 실행************************
준비 끝
준비까지 :  19.807896375656128 초
복사 끝
226.6729474067688 초 걸려 작업 완료
************************ 2022-11-09 16:53:01.893380 함수 실행************************
준비 끝
준비까지 :  13.516995668411255 초
복사 끝
240.40218234062195 초 걸려 작업 완료
************************ 2022-11-09 17:03:02.517350 함수 실행************************
준비 끝
준비까지 :  16.377715587615967 초
복사 끝
245.53654193878174 초 걸려 작업 완료
************************ 2022-11-09 17:13:02.212816 함수 실행************************
준비 끝
준비까지 :  14.09217643737793 초
복사 끝
241.10337018966675 초 걸려 작업 완료
************************ 2022-11-09 17:23:02.403273 함수 실행************************
준비 끝
준비까지 :  13.941535234451294 초
복사 끝
232.0626735687256 초 걸려 작업 완료
************************ 2022-11-09 17:33:02.475844 함수 실행************************
준비 끝
준비까지 :  13.803631782531738 초
복사 끝
227.0275239944458 초 걸려 작업 완료
************************ 2022-11-09 17:43:02.647499 함수 실행************************
준비 끝
준비까지 :  15.502337217330933 초
복사 끝
220.84637022018433 초 걸려 작업 완료
************************ 2022-11-09 17:53:02.606274 함수 실행************************
준비 끝
준비까지 :  12.94299864768982 초
복사 끝
234.45257115364075 초 걸려 작업 완료
************************ 2022-11-09 18:03:02.257237 함수 실행************************
준비 끝
준비까지 :  14.595967292785645 초
복사 끝
200.5104043483734 초 걸려 작업 완료
************************ 2022-11-09 18:13:01.788339 함수 실행************************
준비 끝
준비까지 :  15.454888582229614 초
복사 끝
220.68766355514526 초 걸려 작업 완료
************************ 2022-11-09 18:23:02.376206 함수 실행************************
준비 끝
준비까지 :  13.421066761016846 초
복사 끝
225.51179838180542 초 걸려 작업 완료
************************ 2022-11-09 18:33:02.131769 함수 실행************************
준비 끝
준비까지 :  15.812023401260376 초
복사 끝
212.77303671836853 초 걸려 작업 완료
************************ 2022-11-09 18:43:01.839909 함수 실행************************
준비 끝
준비까지 :  15.974329233169556 초
복사 끝
249.30111074447632 초 걸려 작업 완료
************************ 2022-11-09 18:53:02.223366 함수 실행************************
준비 끝
준비까지 :  12.89989161491394 초
복사 끝
208.55006623268127 초 걸려 작업 완료
************************ 2022-11-09 19:03:02.271935 함수 실행************************
준비 끝
준비까지 :  18.147454738616943 초
복사 끝
246.6745011806488 초 걸려 작업 완료
************************ 2022-11-09 19:13:01.800177 함수 실행************************
준비 끝
준비까지 :  13.047481298446655 초
복사 끝
238.11963629722595 초 걸려 작업 완료
************************ 2022-11-09 19:23:02.121971 함수 실행************************
준비 끝
준비까지 :  13.558044910430908 초
복사 끝
224.7001030445099 초 걸려 작업 완료
************************ 2022-11-09 19:33:02.190813 함수 실행************************
준비 끝
준비까지 :  13.859673261642456 초
복사 끝
222.84890151023865 초 걸려 작업 완료
************************ 2022-11-09 19:43:02.043152 함수 실행************************
준비 끝
준비까지 :  14.821535587310791 초
복사 끝
238.36822032928467 초 걸려 작업 완료
************************ 2022-11-09 19:53:02.375783 함수 실행************************
준비 끝
준비까지 :  12.988419532775879 초
복사 끝
233.29298615455627 초 걸려 작업 완료
************************ 2022-11-09 20:03:02.644129 함수 실행************************
준비 끝
준비까지 :  18.32766366004944 초
복사 끝
237.0798408985138 초 걸려 작업 완료
************************ 2022-11-09 20:13:02.709832 함수 실행************************
준비 끝
준비까지 :  14.526304721832275 초
복사 끝
224.9184455871582 초 걸려 작업 완료
************************ 2022-11-09 20:23:02.535997 함수 실행************************
준비 끝
준비까지 :  18.642762660980225 초
복사 끝
240.820645570755 초 걸려 작업 완료
************************ 2022-11-09 20:33:02.423297 함수 실행************************
준비 끝
준비까지 :  20.37878704071045 초
복사 끝
255.42499351501465 초 걸려 작업 완료
************************ 2022-11-09 20:43:01.988192 함수 실행************************
준비 끝
준비까지 :  16.7575261592865 초
복사 끝
230.38355207443237 초 걸려 작업 완료
************************ 2022-11-09 20:53:02.333765 함수 실행************************
준비 끝
준비까지 :  13.322689771652222 초
복사 끝
267.4658536911011 초 걸려 작업 완료
************************ 2022-11-09 21:03:01.817183 함수 실행************************
준비 끝
준비까지 :  18.84105682373047 초
복사 끝
251.8004972934723 초 걸려 작업 완료
************************ 2022-11-09 21:13:02.619725 함수 실행************************
준비 끝
준비까지 :  14.768444776535034 초
복사 끝
232.46877694129944 초 걸려 작업 완료
************************ 2022-11-09 21:23:02.263605 함수 실행************************
준비 끝
준비까지 :  18.99371647834778 초
복사 끝
272.56575536727905 초 걸려 작업 완료
************************ 2022-11-09 21:33:01.817781 함수 실행************************
준비 끝
준비까지 :  14.31559944152832 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 21:43:02.570694 함수 실행************************
준비 끝
준비까지 :  17.270607233047485 초
복사 끝
246.16908025741577 초 걸려 작업 완료
************************ 2022-11-09 21:53:02.671898 함수 실행************************
준비 끝
준비까지 :  14.2665696144104 초
복사 끝
224.58831810951233 초 걸려 작업 완료
************************ 2022-11-09 22:03:02.428908 함수 실행************************
준비 끝
준비까지 :  15.619705438613892 초
복사 끝
227.66712975502014 초 걸려 작업 완료
************************ 2022-11-09 22:13:02.096143 함수 실행************************
준비 끝
준비까지 :  19.517287969589233 초
복사 끝
254.8802707195282 초 걸려 작업 완료
************************ 2022-11-09 22:23:02.412256 함수 실행************************
준비 끝
준비까지 :  23.365192413330078 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 22:33:02.663629 함수 실행************************
준비 끝
준비까지 :  17.354750156402588 초
복사 끝
258.23980712890625 초 걸려 작업 완료
************************ 2022-11-09 22:43:02.475592 함수 실행************************
준비 끝
준비까지 :  16.375627279281616 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 22:53:02.257854 함수 실행************************
준비 끝
준비까지 :  12.517378807067871 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 23:03:02.033850 함수 실행************************
준비 끝
준비까지 :  15.71086311340332 초
복사 끝
238.05718874931335 초 걸려 작업 완료
************************ 2022-11-09 23:13:02.392196 함수 실행************************
준비 끝
준비까지 :  15.055968046188354 초
복사 끝
233.20463013648987 초 걸려 작업 완료
************************ 2022-11-09 23:23:02.650416 함수 실행************************
준비 끝
준비까지 :  14.434063911437988 초
복사 끝
246.9701850414276 초 걸려 작업 완료
************************ 2022-11-09 23:33:02.590407 함수 실행************************
준비 끝
준비까지 :  22.68655300140381 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 23:43:02.463194 함수 실행************************
준비 끝
준비까지 :  13.318221807479858 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-09 23:53:01.959862 함수 실행************************
준비 끝
준비까지 :  17.192437648773193 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:03:01.849716 함수 실행************************
준비 끝
준비까지 :  15.334407091140747 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:13:02.380313 함수 실행************************
준비 끝
준비까지 :  16.3725848197937 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:23:02.142934 함수 실행************************
준비 끝
준비까지 :  15.230524778366089 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:33:02.294919 함수 실행************************
준비 끝
준비까지 :  22.407798051834106 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:43:02.116273 함수 실행************************
준비 끝
준비까지 :  18.187500715255737 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 00:53:02.349996 함수 실행************************
준비 끝
준비까지 :  18.769631385803223 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:03:02.195545 함수 실행************************
준비 끝
준비까지 :  20.446768045425415 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:13:02.348190 함수 실행************************
준비 끝
준비까지 :  53.84993004798889 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:23:02.532868 함수 실행************************
준비 끝
준비까지 :  11.553563833236694 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:33:02.641673 함수 실행************************
준비 끝
준비까지 :  12.646942377090454 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:43:03.207419 함수 실행************************
준비 끝
준비까지 :  15.039024114608765 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 01:53:02.405910 함수 실행************************
준비 끝
준비까지 :  15.796961069107056 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 02:03:02.428769 함수 실행************************
준비 끝
준비까지 :  15.282196283340454 초
복사 끝
216.75947046279907 초 걸려 작업 완료
************************ 2022-11-10 02:13:02.329470 함수 실행************************
준비 끝
준비까지 :  15.553840398788452 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 02:23:02.546049 함수 실행************************
준비 끝
준비까지 :  14.436750650405884 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 02:33:02.495582 함수 실행************************
준비 끝
준비까지 :  15.59269118309021 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 02:43:02.202811 함수 실행************************
준비 끝
준비까지 :  17.22869873046875 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 02:53:02.313636 함수 실행************************
준비 끝
준비까지 :  20.808582067489624 초
복사 끝
251.0651831626892 초 걸려 작업 완료
************************ 2022-11-10 03:03:02.762488 함수 실행************************
준비 끝
준비까지 :  21.91854476928711 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 03:13:01.972823 함수 실행************************
준비 끝
준비까지 :  16.036524772644043 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 03:23:02.494038 함수 실행************************
준비 끝
준비까지 :  15.140461921691895 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 03:33:02.241762 함수 실행************************
준비 끝
준비까지 :  22.05848526954651 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 03:43:02.255095 함수 실행************************
준비 끝
준비까지 :  22.902348279953003 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 03:53:02.342367 함수 실행************************
준비 끝
준비까지 :  14.570472240447998 초
복사 끝
238.98156094551086 초 걸려 작업 완료
************************ 2022-11-10 04:03:02.384349 함수 실행************************
준비 끝
준비까지 :  22.736675024032593 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 04:13:01.816590 함수 실행************************
준비 끝
준비까지 :  14.818914890289307 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 04:23:02.225089 함수 실행************************
준비 끝
준비까지 :  14.720554828643799 초
복사 끝
240.43826746940613 초 걸려 작업 완료
************************ 2022-11-10 04:33:02.633234 함수 실행************************
준비 끝
준비까지 :  16.63776659965515 초
============== 시작 에서 문제가 생겼습니다.==============
************************ 2022-11-10 04:43:02.461611 함수 실행************************
준비 끝
준비까지 :  14.219506978988647 초
복사 끝
251.92502903938293 초 걸려 작업 완료
************************ 2022-11-10 04:53:02.516985 함수 실행************************
준비 끝
준비까지 :  14.930420160293579 초
복사 끝
323.8170211315155 초 걸려 작업 완료
************************ 2022-11-10 05:03:02.384426 함수 실행************************
준비 끝
준비까지 :  14.432649850845337 초
복사 끝
94.70898365974426 초 걸려 작업 완료
************************ 2022-11-10 05:13:02.669241 함수 실행************************
준비 끝
준비까지 :  14.659967184066772 초
복사 끝
94.5656476020813 초 걸려 작업 완료
************************ 2022-11-10 05:23:02.475751 함수 실행************************
준비 끝
준비까지 :  14.799523830413818 초
복사 끝
663.3736126422882 초 걸려 작업 완료
************************ 2022-11-10 05:33:02.589862 함수 실행************************
준비 끝
준비까지 :  24.76000142097473 초
복사 끝
166.23930644989014 초 걸려 작업 완료
************************ 2022-11-10 05:43:02.035894 함수 실행************************
준비 끝
준비까지 :  13.749934434890747 초
복사 끝
86.0926947593689 초 걸려 작업 완료
************************ 2022-11-10 05:53:02.316731 함수 실행************************
준비 끝
준비까지 :  15.983120203018188 초
복사 끝
111.1670310497284 초 걸려 작업 완료
************************ 2022-11-10 06:03:02.551228 함수 실행************************
준비 끝
준비까지 :  14.489394664764404 초
복사 끝
116.73375272750854 초 걸려 작업 완료
************************ 2022-11-10 06:13:02.442495 함수 실행************************
준비 끝
준비까지 :  22.174445152282715 초
복사 끝
137.25077962875366 초 걸려 작업 완료
************************ 2022-11-10 06:23:01.994291 함수 실행************************
준비 끝
준비까지 :  17.664355039596558 초
복사 끝
143.30153059959412 초 걸려 작업 완료
************************ 2022-11-10 06:33:02.383070 함수 실행************************
준비 끝
준비까지 :  22.629139184951782 초
복사 끝
167.3778579235077 초 걸려 작업 완료
************************ 2022-11-10 06:43:02.712847 함수 실행************************
준비 끝
준비까지 :  16.726126432418823 초
복사 끝
140.13475704193115 초 걸려 작업 완료
************************ 2022-11-10 06:53:02.244684 함수 실행************************
준비 끝
준비까지 :  22.73851251602173 초
복사 끝
147.41504526138306 초 걸려 작업 완료
************************ 2022-11-10 07:03:03.128147 함수 실행************************
준비 끝
준비까지 :  15.368911266326904 초
복사 끝
122.069016456604 초 걸려 작업 완료
************************ 2022-11-10 07:13:03.153500 함수 실행************************
준비 끝
준비까지 :  15.181374549865723 초
복사 끝
130.76801753044128 초 걸려 작업 완료
************************ 2022-11-10 07:23:02.104109 함수 실행************************
준비 끝
준비까지 :  13.1806480884552 초
복사 끝
151.83165073394775 초 걸려 작업 완료
************************ 2022-11-10 07:33:02.129694 함수 실행************************
준비 끝
준비까지 :  19.553983211517334 초
복사 끝
139.83222365379333 초 걸려 작업 완료
************************ 2022-11-10 07:43:01.866959 함수 실행************************
준비 끝
준비까지 :  13.970177173614502 초
복사 끝
95.69620656967163 초 걸려 작업 완료
************************ 2022-11-10 07:53:02.643375 함수 실행************************
준비 끝
준비까지 :  15.0109121799469 초
복사 끝
123.79337072372437 초 걸려 작업 완료
************************ 2022-11-10 08:03:01.977825 함수 실행************************
준비 끝
준비까지 :  14.617703676223755 초
복사 끝
87.83749771118164 초 걸려 작업 완료
************************ 2022-11-10 08:13:02.998117 함수 실행************************
준비 끝
준비까지 :  20.46042227745056 초
복사 끝
131.94251704216003 초 걸려 작업 완료
************************ 2022-11-10 08:23:02.053527 함수 실행************************
준비 끝
준비까지 :  13.111222743988037 초
복사 끝
82.4566011428833 초 걸려 작업 완료
************************ 2022-11-10 08:33:02.651904 함수 실행************************
준비 끝
준비까지 :  24.471758365631104 초
복사 끝
114.66422581672668 초 걸려 작업 완료
************************ 2022-11-10 08:43:02.271905 함수 실행************************
준비 끝
준비까지 :  14.231028079986572 초
복사 끝
93.01236081123352 초 걸려 작업 완료
************************ 2022-11-10 08:53:02.475868 함수 실행************************
준비 끝
준비까지 :  22.823205709457397 초
복사 끝
140.41628456115723 초 걸려 작업 완료
************************ 2022-11-10 09:03:02.029094 함수 실행************************
준비 끝
준비까지 :  19.81185030937195 초
복사 끝
109.50662922859192 초 걸려 작업 완료
************************ 2022-11-10 09:13:02.653531 함수 실행************************
준비 끝
준비까지 :  20.14986777305603 초
복사 끝
148.5381679534912 초 걸려 작업 완료
************************ 2022-11-10 09:23:02.169876 함수 실행************************
준비 끝
준비까지 :  13.638197898864746 초
복사 끝
154.78509044647217 초 걸려 작업 완료
************************ 2022-11-10 09:33:02.067502 함수 실행************************
준비 끝
준비까지 :  19.45708441734314 초
복사 끝
168.8496549129486 초 걸려 작업 완료
************************ 2022-11-10 09:43:01.975540 함수 실행************************
준비 끝
준비까지 :  19.88614511489868 초
복사 끝
133.70937967300415 초 걸려 작업 완료
************************ 2022-11-10 09:53:01.762279 함수 실행************************
준비 끝
준비까지 :  14.366451501846313 초
복사 끝
87.6097264289856 초 걸려 작업 완료
************************ 2022-11-10 10:03:02.443697 함수 실행************************
준비 끝
준비까지 :  20.25717806816101 초
복사 끝
109.05843138694763 초 걸려 작업 완료
************************ 2022-11-10 10:13:02.691984 함수 실행************************
준비 끝
준비까지 :  16.39347743988037 초
복사 끝
146.92590403556824 초 걸려 작업 완료
************************ 2022-11-10 10:23:01.853077 함수 실행************************
준비 끝
준비까지 :  13.195744276046753 초
복사 끝
111.31140685081482 초 걸려 작업 완료
************************ 2022-11-10 10:33:02.407414 함수 실행************************
준비 끝
준비까지 :  13.594250440597534 초
복사 끝
146.389817237854 초 걸려 작업 완료
************************ 2022-11-10 10:43:01.847251 함수 실행************************
준비 끝
준비까지 :  13.794665813446045 초
복사 끝
111.54442644119263 초 걸려 작업 완료
************************ 2022-11-10 10:53:02.493417 함수 실행************************
준비 끝
준비까지 :  14.132949590682983 초
복사 끝
84.84116721153259 초 걸려 작업 완료
************************ 2022-11-10 11:03:02.494694 함수 실행************************
준비 끝
준비까지 :  13.79278016090393 초
복사 끝
95.35963225364685 초 걸려 작업 완료
************************ 2022-11-10 11:13:02.530921 함수 실행************************
준비 끝
준비까지 :  13.36484670639038 초
복사 끝
107.68486261367798 초 걸려 작업 완료
************************ 2022-11-10 11:23:02.405086 함수 실행************************
준비 끝
준비까지 :  12.946801900863647 초
복사 끝
91.11268663406372 초 걸려 작업 완료
************************ 2022-11-10 11:33:02.632628 함수 실행************************
준비 끝
준비까지 :  13.385972499847412 초
복사 끝
102.78487730026245 초 걸려 작업 완료
************************ 2022-11-10 11:43:02.616911 함수 실행************************
준비 끝
준비까지 :  13.326593399047852 초
복사 끝
100.93555808067322 초 걸려 작업 완료
************************ 2022-11-10 11:53:02.633673 함수 실행************************
준비 끝
준비까지 :  13.967347860336304 초
복사 끝
103.24882912635803 초 걸려 작업 완료
************************ 2022-11-10 12:03:02.102623 함수 실행************************
준비 끝
준비까지 :  13.192458152770996 초
복사 끝
108.08650255203247 초 걸려 작업 완료
************************ 2022-11-10 12:13:01.858033 함수 실행************************
준비 끝
준비까지 :  12.635999917984009 초
복사 끝
99.74230742454529 초 걸려 작업 완료
************************ 2022-11-10 12:23:01.968450 함수 실행************************
준비 끝
준비까지 :  12.043162822723389 초
복사 끝
106.59217095375061 초 걸려 작업 완료
************************ 2022-11-10 12:33:02.736958 함수 실행************************
준비 끝
준비까지 :  13.537203550338745 초
복사 끝
101.78910994529724 초 걸려 작업 완료
************************ 2022-11-10 12:43:02.532940 함수 실행************************
준비 끝
준비까지 :  13.794368505477905 초
복사 끝
86.32551121711731 초 걸려 작업 완료
************************ 2022-11-10 12:53:02.233672 함수 실행************************
준비 끝
준비까지 :  13.866088390350342 초
복사 끝
105.5006320476532 초 걸려 작업 완료
************************ 2022-11-10 13:03:02.246253 함수 실행************************
준비 끝
준비까지 :  15.916404247283936 초
복사 끝
102.67665433883667 초 걸려 작업 완료
************************ 2022-11-10 13:13:02.273214 함수 실행************************
준비 끝
준비까지 :  13.339274883270264 초
복사 끝
105.4806718826294 초 걸려 작업 완료
